/**
 * TypeScript definitions for typography configuration
 *
 * Auto-generated by build.js - DO NOT EDIT MANUALLY
 */

export type TypographyVariant =
  | 'display-lg'
  | 'display'
  | 'heading-2xl'
  | 'heading-xl'
  | 'heading-lg'
  | 'heading-md'
  | 'heading-sm'
  | 'heading-xs'
  | 'heading-2xs'
  | 'body'
  | 'body-strong'
  | 'body-sm'
  | 'body-sm-strong'
  | 'footnote-lg'
  | 'footnote'
  | 'overline';

export type Breakpoint = 'mobile' | 'tablet' | 'desktop' | 'desktop-hd';

export interface TypographyStyle {
  fontSize: number;
  fontWeight: string;
  lineHeight: number;
  letterSpacing: number;
  fontFamily: string;
  textTransform?: 'uppercase';
}

export interface BreakpointTypography {
  fontSize: Record<TypographyVariant, number>;
  fontWeight: Record<TypographyVariant, string>;
  lineHeight: Record<TypographyVariant, number>;
  letterSpacing: Record<TypographyVariant, number>;
  fontFamilyNative: Record<TypographyVariant, string>;
  fontFamilyWeb: Record<TypographyVariant, string>;
}

export const breakpoints: Record<Breakpoint, number>;
export const screenNames: Array<'tablet' | 'desktop' | 'desktop-hd'>;
export const typographyVariants: TypographyVariant[];
export const typography: Record<Breakpoint, BreakpointTypography>;

export const fontFamily: Record<TypographyVariant, string>;
export const fontFamilyNative: Record<TypographyVariant, string>;
export const fontFamilyWeb: Record<TypographyVariant, string>;
export const fontSize: Record<TypographyVariant, number>;
export const fontWeight: Record<TypographyVariant, string>;
export const lineHeight: Record<TypographyVariant, number>;
export const letterSpacing: Record<TypographyVariant, number>;

export const textAlignClasses: Record<'left' | 'center' | 'right' | 'justify', string>;
export const defaultTextColorClass: string;
export const textColorNames: string[];

export const getFontFamilyForWeight: (familyName: string, weight: string) => string;
export const getTypographyStyle: (variant: TypographyVariant, breakpoint?: Breakpoint) => TypographyStyle;
export const getResponsiveTypographyClasses: (variant: TypographyVariant) => string;

declare const _default: {
  breakpoints: typeof breakpoints;
  screenNames: typeof screenNames;
  typographyVariants: typeof typographyVariants;
  typography: typeof typography;
  fontFamily: typeof fontFamily;
  fontFamilyNative: typeof fontFamilyNative;
  fontFamilyWeb: typeof fontFamilyWeb;
  fontSize: typeof fontSize;
  fontWeight: typeof fontWeight;
  lineHeight: typeof lineHeight;
  letterSpacing: typeof letterSpacing;
  textAlignClasses: typeof textAlignClasses;
  defaultTextColorClass: typeof defaultTextColorClass;
  getFontFamilyForWeight: typeof getFontFamilyForWeight;
  getTypographyStyle: typeof getTypographyStyle;
  getResponsiveTypographyClasses: typeof getResponsiveTypographyClasses;
  textColorNames: typeof textColorNames;
};

export default _default;
